# Site settings
title: Emory Arts Underground
email: emoryartsunderground@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Emory Arts Underground is a student-run arts organization at Emory University in Atlanta, GA that aims to increase the accessibility of arts education and to uncover the underground arts culture on campus.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  emoryartsunderground

# Build settings
markdown: kramdown
permalink: pretty
